// =============================================================================
// FIFA World Cup 2026 — Annex C 3rd-place allocation table BUILD & VALIDATE
// -----------------------------------------------------------------------------
// 公式規則 付属書C の「3位通過8チームを R32 の8つの1位スロットへ割り当てる」
// 495通りの対応表を、転記ミス検出付きで取り込み src/data/thirdPlaceAllocation.ts
// を生成する開発用スクリプト。
//
//   実行:  node scripts/build-annexc.mjs
//
// 検証内容:
//   1) 行数がちょうど 495
//   2) 各行の通過グループが A-L から相異なる8個
//   3) 495行のグループ集合が C(12,8)=495 を重複なく完全網羅
//   4) 各行の割り当てが通過グループの順列（過不足なし）
//   5) 各割り当てが公式プール制約に適合
// 検証に1つでも失敗したら出力せず、該当行を表示して終了する。
// =============================================================================

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// 3位チームと対戦する1位スロット（公式表の列順: 1A 1B 1D 1E 1G 1I 1K 1L）
const SLOTS = ['A', 'B', 'D', 'E', 'G', 'I', 'K', 'L'];

// 各スロットの公式プール（そのスロットに入りうる3位の所属グループ）
const POOLS = {
  A: ['C', 'E', 'F', 'H', 'I'],
  B: ['E', 'F', 'G', 'I', 'J'],
  D: ['B', 'E', 'F', 'I', 'J'],
  E: ['A', 'B', 'C', 'D', 'F'],
  G: ['A', 'E', 'H', 'I', 'J'],
  I: ['C', 'D', 'F', 'G', 'H'],
  K: ['D', 'E', 'I', 'J', 'L'],
  L: ['E', 'H', 'I', 'J', 'K'],
};

// 生データ: "<行番号> <通過8グループ> <割り当て8文字(列順 A B D E G I K L)>"
// 出典: ja.wikipedia「2026 FIFAワールドカップ・ノックアウトステージ」ラウンド32の組み合わせ
const RAW = `
1 EFGHIJKL EJIFHGLK
2 DFGHIJKL HGIDJFLK
3 DEGHIJKL EJIDHGLK
4 DEFHIJKL EJIDHFLK
5 DEFGIJKL EGIDJFLK
6 DEFGHJKL EGJDHFLK
7 DEFGHIKL EGIDHFLK
8 DEFGHIJL EGJDHFLI
9 DEFGHIJK EGJDHFIK
10 CFGHIJKL HGICJFLK
11 CEGHIJKL EJICHGLK
12 CEFHIJKL EJICHFLK
13 CEFGIJKL EGICJFLK
14 CEFGHJKL EGJCHFLK
15 CEFGHIKL EGICHFLK
16 CEFGHIJL EGJCHFLI
17 CEFGHIJK EGJCHFIK
18 CDGHIJKL HGICJDLK
19 CDFHIJKL CJIDHFLK
20 CDFGIJKL CGIDJFLK
21 CDFGHJKL CGJDHFLK
22 CDFGHIKL CGIDHFLK
23 CDFGHIJL CGJDHFLI
24 CDFGHIJK CGJDHFIK
25 CDEHIJKL EJICHDLK
26 CDEGIJKL EGICJDLK
27 CDEGHJKL EGJCHDLK
28 CDEGHIKL EGICHDLK
29 CDEGHIJL EGJCHDLI
30 CDEGHIJK EGJCHDIK
31 CDEFIJKL CJEDIFLK
32 CDEFHJKL CJEDHFLK
33 CDEFHIKL CEIDHFLK
34 CDEFHIJL CJEDHFLI
35 CDEFHIJK CJEDHFIK
36 CDEFGJKL CGEDJFLK
37 CDEFGIKL CGEDIFLK
38 CDEFGIJL CGEDJFLI
39 CDEFGIJK CGEDJFIK
40 CDEFGHKL CGEDHFLK
41 CDEFGHJL CGJDHFLE
42 CDEFGHJK CGJDHFEK
43 CDEFGHIL CGEDHFLI
44 CDEFGHIK CGEDHFIK
45 CDEFGHIJ CGJDHFEI
46 BFGHIJKL HJBFIGLK
47 BEGHIJKL EJIBHGLK
48 BEFHIJKL EJBFIHLK
49 BEFGIJKL EJBFIGLK
50 BEFGHJKL EJBFHGLK
51 BEFGHIKL EGBFIHLK
52 BEFGHIJL EJBFHGLI
53 BEFGHIJK EJBFHGIK
54 BDGHIJKL HJBDIGLK
55 BDFHIJKL HJBDIFLK
56 BDFGIJKL IGBDJFLK
57 BDFGHJKL HGBDJFLK
58 BDFGHIKL HGBDIFLK
59 BDFGHIJL HGBDJFLI
60 BDFGHIJK HGBDJFIK
61 BDEHIJKL EJBDIHLK
62 BDEGIJKL EJBDIGLK
63 BDEGHJKL EJBDHGLK
64 BDEGHIKL EGBDIHLK
65 BDEGHIJL EJBDHGLI
66 BDEGHIJK EJBDHGIK
67 BDEFIJKL EJBDIFLK
68 BDEFHJKL EJBDHFLK
69 BDEFHIKL EIBDHFLK
70 BDEFHIJL EJBDHFLI
71 BDEFHIJK EJBDHFIK
72 BDEFGJKL EGBDJFLK
73 BDEFGIKL EGBDIFLK
74 BDEFGIJL EGBDJFLI
75 BDEFGIJK EGBDJFIK
76 BDEFGHKL EGBDHFLK
77 BDEFGHJL HGBDJFLE
78 BDEFGHJK HGBDJFEK
79 BDEFGHIL EGBDHFLI
80 BDEFGHIK EGBDHFIK
81 BDEFGHIJ HGBDJFEI
82 BCGHIJKL HJBCIGLK
83 BCFHIJKL HJBCIFLK
84 BCFGIJKL IGBCJFLK
85 BCFGHJKL HGBCJFLK
86 BCFGHIKL HGBCIFLK
87 BCFGHIJL HGBCJFLI
88 BCFGHIJK HGBCJFIK
89 BCEHIJKL EJBCIHLK
90 BCEGIJKL EJBCIGLK
91 BCEGHJKL EJBCHGLK
92 BCEGHIKL EGBCIHLK
93 BCEGHIJL EJBCHGLI
94 BCEGHIJK EJBCHGIK
95 BCEFIJKL EJBCIFLK
96 BCEFHJKL EJBCHFLK
97 BCEFHIKL EIBCHFLK
98 BCEFHIJL EJBCHFLI
99 BCEFHIJK EJBCHFIK
100 BCEFGJKL EGBCJFLK
101 BCEFGIKL EGBCIFLK
102 BCEFGIJL EGBCJFLI
103 BCEFGIJK EGBCJFIK
104 BCEFGHKL EGBCHFLK
105 BCEFGHJL HGBCJFLE
106 BCEFGHJK HGBCJFEK
107 BCEFGHIL EGBCHFLI
108 BCEFGHIK EGBCHFIK
109 BCEFGHIJ HGBCJFEI
110 BCDHIJKL HJBCIDLK
111 BCDGIJKL IGBCJDLK
112 BCDGHJKL HGBCJDLK
113 BCDGHIKL HGBCIDLK
114 BCDGHIJL HGBCJDLI
115 BCDGHIJK HGBCJDIK
116 BCDFIJKL CJBDIFLK
117 BCDFHJKL CJBDHFLK
118 BCDFHIKL CIBDHFLK
119 BCDFHIJL CJBDHFLI
120 BCDFHIJK CJBDHFIK
121 BCDFGJKL CGBDJFLK
122 BCDFGIKL CGBDIFLK
123 BCDFGIJL CGBDJFLI
124 BCDFGIJK CGBDJFIK
125 BCDFGHKL CGBDHFLK
126 BCDFGHJL CGBDHFLJ
127 BCDFGHJK HGBCJFDK
128 BCDFGHIL CGBDHFLI
129 BCDFGHIK CGBDHFIK
130 BCDFGHIJ HGBCJFDI
131 BCDEIJKL EJBCIDLK
132 BCDEHJKL EJBCHDLK
133 BCDEHIKL EIBCHDLK
134 BCDEHIJL EJBCHDLI
135 BCDEHIJK EJBCHDIK
136 BCDEGJKL EGBCJDLK
137 BCDEGIKL EGBCIDLK
138 BCDEGIJL EGBCJDLI
139 BCDEGIJK EGBCJDIK
140 BCDEGHKL EGBCHDLK
141 BCDEGHJL HGBCJDLE
142 BCDEGHJK HGBCJDEK
143 BCDEGHIL EGBCHDLI
144 BCDEGHIK EGBCHDIK
145 BCDEGHIJ HGBCJDEI
146 BCDEFJKL CJBDEFLK
147 BCDEFIKL CEBDIFLK
148 BCDEFIJL CJBDEFLI
149 BCDEFIJK CJBDEFIK
150 BCDEFHKL CEBDHFLK
151 BCDEFHJL CJBDHFLE
152 BCDEFHJK CJBDHFEK
153 BCDEFHIL CEBDHFLI
154 BCDEFHIK CEBDHFIK
155 BCDEFHIJ CJBDHFEI
156 BCDEFGKL CGBDEFLK
157 BCDEFGJL CGBDJFLE
158 BCDEFGJK CGBDJFEK
159 BCDEFGIL CGBDEFLI
160 BCDEFGIK CGBDEFIK
161 BCDEFGIJ CGBDJFEI
162 BCDEFGHL CGBDHFLE
163 BCDEFGHK CGBDHFEK
164 BCDEFGHJ HGBCJFDE
165 BCDEFGHI CGBDHFEI
166 AFGHIJKL HJIFAGLK
167 AEGHIJKL EJIAHGLK
168 AEFHIJKL EJIFAHLK
169 AEFGIJKL EJIFAGLK
170 AEFGHJKL EGJFAHLK
171 AEFGHIKL EGIFAHLK
172 AEFGHIJL EGJFAHLI
173 AEFGHIJK EGJFAHIK
174 ADGHIJKL HJIDAGLK
175 ADFHIJKL HJIDAFLK
176 ADFGIJKL IGJDAFLK
177 ADFGHJKL HGJDAFLK
178 ADFGHIKL HGIDAFLK
179 ADFGHIJL HGJDAFLI
180 ADFGHIJK HGJDAFIK
181 ADEHIJKL EJIDAHLK
182 ADEGIJKL EJIDAGLK
183 ADEGHJKL EGJDAHLK
184 ADEGHIKL EGIDAHLK
185 ADEGHIJL EGJDAHLI
186 ADEGHIJK EGJDAHIK
187 ADEFIJKL EJIDAFLK
188 ADEFHJKL HJEDAFLK
189 ADEFHIKL HEIDAFLK
190 ADEFHIJL HJEDAFLI
191 ADEFHIJK HJEDAFIK
192 ADEFGJKL EGJDAFLK
193 ADEFGIKL EGIDAFLK
194 ADEFGIJL EGJDAFLI
195 ADEFGIJK EGJDAFIK
196 ADEFGHKL HGEDAFLK
197 ADEFGHJL HGJDAFLE
198 ADEFGHJK HGJDAFEK
199 ADEFGHIL HGEDAFLI
200 ADEFGHIK HGEDAFIK
201 ADEFGHIJ HGJDAFEI
202 ACGHIJKL HJICAGLK
203 ACFHIJKL HJICAFLK
204 ACFGIJKL IGJCAFLK
205 ACFGHJKL HGJCAFLK
206 ACFGHIKL HGICAFLK
207 ACFGHIJL HGJCAFLI
208 ACFGHIJK HGJCAFIK
209 ACEHIJKL EJICAHLK
210 ACEGIJKL EJICAGLK
211 ACEGHJKL EGJCAHLK
212 ACEGHIKL EGICAHLK
213 ACEGHIJL EGJCAHLI
214 ACEGHIJK EGJCAHIK
215 ACEFIJKL EJICAFLK
216 ACEFHJKL HJECAFLK
217 ACEFHIKL HEICAFLK
218 ACEFHIJL HJECAFLI
219 ACEFHIJK HJECAFIK
220 ACEFGJKL EGJCAFLK
221 ACEFGIKL EGICAFLK
222 ACEFGIJL EGJCAFLI
223 ACEFGIJK EGJCAFIK
224 ACEFGHKL HGECAFLK
225 ACEFGHJL HGJCAFLE
226 ACEFGHJK HGJCAFEK
227 ACEFGHIL HGECAFLI
228 ACEFGHIK HGECAFIK
229 ACEFGHIJ HGJCAFEI
230 ACDHIJKL HJICADLK
231 ACDGIJKL IGJCADLK
232 ACDGHJKL HGJCADLK
233 ACDGHIKL HGICADLK
234 ACDGHIJL HGJCADLI
235 ACDGHIJK HGJCADIK
236 ACDFIJKL CJIDAFLK
237 ACDFHJKL HJFCADLK
238 ACDFHIKL HFICADLK
239 ACDFHIJL HJFCADLI
240 ACDFHIJK HJFCADIK
241 ACDFGJKL CGJDAFLK
242 ACDFGIKL CGIDAFLK
243 ACDFGIJL CGJDAFLI
244 ACDFGIJK CGJDAFIK
245 ACDFGHKL HGFCADLK
246 ACDFGHJL CGJDAFLH
247 ACDFGHJK HGJCAFDK
248 ACDFGHIL HGFCADLI
249 ACDFGHIK HGFCADIK
250 ACDFGHIJ HGJCAFDI
251 ACDEIJKL EJICADLK
252 ACDEHJKL HJECADLK
253 ACDEHIKL HEICADLK
254 ACDEHIJL HJECADLI
255 ACDEHIJK HJECADIK
256 ACDEGJKL EGJCADLK
257 ACDEGIKL EGICADLK
258 ACDEGIJL EGJCADLI
259 ACDEGIJK EGJCADIK
260 ACDEGHKL HGECADLK
261 ACDEGHJL HGJCADLE
262 ACDEGHJK HGJCADEK
263 ACDEGHIL HGECADLI
264 ACDEGHIK HGECADIK
265 ACDEGHIJ HGJCADEI
266 ACDEFJKL CJEDAFLK
267 ACDEFIKL CEIDAFLK
268 ACDEFIJL CJEDAFLI
269 ACDEFIJK CJEDAFIK
270 ACDEFHKL HEFCADLK
271 ACDEFHJL HJFCADLE
272 ACDEFHJK HJECAFDK
273 ACDEFHIL HEFCADLI
274 ACDEFHIK HEFCADIK
275 ACDEFHIJ HJECAFDI
276 ACDEFGKL CGEDAFLK
277 ACDEFGJL CGJDAFLE
278 ACDEFGJK CGJDAFEK
279 ACDEFGIL CGEDAFLI
280 ACDEFGIK CGEDAFIK
281 ACDEFGIJ CGJDAFEI
282 ACDEFGHL HGFCADLE
283 ACDEFGHK HGECAFDK
284 ACDEFGHJ HGJCAFDE
285 ACDEFGHI HGECAFDI
286 ABGHIJKL HJBAIGLK
287 ABFHIJKL HJBAIFLK
288 ABFGIJKL IJBFAGLK
289 ABFGHJKL HJBFAGLK
290 ABFGHIKL HGBAIFLK
291 ABFGHIJL HJBFAGLI
292 ABFGHIJK HJBFAGIK
293 ABEHIJKL EJBAIHLK
294 ABEGIJKL EJBAIGLK
295 ABEGHJKL EJBAHGLK
296 ABEGHIKL EGBAIHLK
297 ABEGHIJL EJBAHGLI
298 ABEGHIJK EJBAHGIK
299 ABEFIJKL EJBAIFLK
300 ABEFHJKL EJBFAHLK
301 ABEFHIKL EIBFAHLK
302 ABEFHIJL EJBFAHLI
303 ABEFHIJK EJBFAHIK
304 ABEFGJKL EJBFAGLK
305 ABEFGIKL EGBAIFLK
306 ABEFGIJL EJBFAGLI
307 ABEFGIJK EJBFAGIK
308 ABEFGHKL EGBFAHLK
309 ABEFGHJL HJBFAGLE
310 ABEFGHJK HJBFAGEK
311 ABEFGHIL EGBFAHLI
312 ABEFGHIK EGBFAHIK
313 ABEFGHIJ HJBFAGEI
314 ABDHIJKL IJBDAHLK
315 ABDGIJKL IJBDAGLK
316 ABDGHJKL HJBDAGLK
317 ABDGHIKL IGBDAHLK
318 ABDGHIJL HJBDAGLI
319 ABDGHIJK HJBDAGIK
320 ABDFIJKL IJBDAFLK
321 ABDFHJKL HJBDAFLK
322 ABDFHIKL HIBDAFLK
323 ABDFHIJL HJBDAFLI
324 ABDFHIJK HJBDAFIK
325 ABDFGJKL FJBDAGLK
326 ABDFGIKL IGBDAFLK
327 ABDFGIJL FJBDAGLI
328 ABDFGIJK FJBDAGIK
329 ABDFGHKL HGBDAFLK
330 ABDFGHJL HGBDAFLJ
331 ABDFGHJK HGBDAFJK
332 ABDFGHIL HGBDAFLI
333 ABDFGHIK HGBDAFIK
334 ABDFGHIJ HGBDAFIJ
335 ABDEIJKL EJBAIDLK
336 ABDEHJKL EJBDAHLK
337 ABDEHIKL EIBDAHLK
338 ABDEHIJL EJBDAHLI
339 ABDEHIJK EJBDAHIK
340 ABDEGJKL EJBDAGLK
341 ABDEGIKL EGBAIDLK
342 ABDEGIJL EJBDAGLI
343 ABDEGIJK EJBDAGIK
344 ABDEGHKL EGBDAHLK
345 ABDEGHJL HJBDAGLE
346 ABDEGHJK HJBDAGEK
347 ABDEGHIL EGBDAHLI
348 ABDEGHIK EGBDAHIK
349 ABDEGHIJ HJBDAGEI
350 ABDEFJKL EJBDAFLK
351 ABDEFIKL EIBDAFLK
352 ABDEFIJL EJBDAFLI
353 ABDEFIJK EJBDAFIK
354 ABDEFHKL HEBDAFLK
355 ABDEFHJL HJBDAFLE
356 ABDEFHJK HJBDAFEK
357 ABDEFHIL HEBDAFLI
358 ABDEFHIK HEBDAFIK
359 ABDEFHIJ HJBDAFEI
360 ABDEFGKL EGBDAFLK
361 ABDEFGJL EGBDAFLJ
362 ABDEFGJK EGBDAFJK
363 ABDEFGIL EGBDAFLI
364 ABDEFGIK EGBDAFIK
365 ABDEFGIJ EGBDAFIJ
366 ABDEFGHL HGBDAFLE
367 ABDEFGHK HGBDAFEK
368 ABDEFGHJ HGBDAFEJ
369 ABDEFGHI HGBDAFEI
370 ABCHIJKL IJBCAHLK
371 ABCGIJKL IJBCAGLK
372 ABCGHJKL HJBCAGLK
373 ABCGHIKL IGBCAHLK
374 ABCGHIJL HJBCAGLI
375 ABCGHIJK HJBCAGIK
376 ABCFIJKL IJBCAFLK
377 ABCFHJKL HJBCAFLK
378 ABCFHIKL HIBCAFLK
379 ABCFHIJL HJBCAFLI
380 ABCFHIJK HJBCAFIK
381 ABCFGJKL CJBFAGLK
382 ABCFGIKL IGBCAFLK
383 ABCFGIJL CJBFAGLI
384 ABCFGIJK CJBFAGIK
385 ABCFGHKL HGBCAFLK
386 ABCFGHJL HGBCAFLJ
387 ABCFGHJK HGBCAFJK
388 ABCFGHIL HGBCAFLI
389 ABCFGHIK HGBCAFIK
390 ABCFGHIJ HGBCAFIJ
391 ABCEIJKL EJBAICLK
392 ABCEHJKL EJBCAHLK
393 ABCEHIKL EIBCAHLK
394 ABCEHIJL EJBCAHLI
395 ABCEHIJK EJBCAHIK
396 ABCEGJKL EJBCAGLK
397 ABCEGIKL EGBAICLK
398 ABCEGIJL EJBCAGLI
399 ABCEGIJK EJBCAGIK
400 ABCEGHKL EGBCAHLK
401 ABCEGHJL HJBCAGLE
402 ABCEGHJK HJBCAGEK
403 ABCEGHIL EGBCAHLI
404 ABCEGHIK EGBCAHIK
405 ABCEGHIJ HJBCAGEI
406 ABCEFJKL EJBCAFLK
407 ABCEFIKL EIBCAFLK
408 ABCEFIJL EJBCAFLI
409 ABCEFIJK EJBCAFIK
410 ABCEFHKL HEBCAFLK
411 ABCEFHJL HJBCAFLE
412 ABCEFHJK HJBCAFEK
413 ABCEFHIL HEBCAFLI
414 ABCEFHIK HEBCAFIK
415 ABCEFHIJ HJBCAFEI
416 ABCEFGKL EGBCAFLK
417 ABCEFGJL EGBCAFLJ
418 ABCEFGJK EGBCAFJK
419 ABCEFGIL EGBCAFLI
420 ABCEFGIK EGBCAFIK
421 ABCEFGIJ EGBCAFIJ
422 ABCEFGHL HGBCAFLE
423 ABCEFGHK HGBCAFEK
424 ABCEFGHJ HGBCAFEJ
425 ABCEFGHI HGBCAFEI
426 ABCDIJKL IJBCADLK
427 ABCDHJKL HJBCADLK
428 ABCDHIKL HIBCADLK
429 ABCDHIJL HJBCADLI
430 ABCDHIJK HJBCADIK
431 ABCDGJKL CJBDAGLK
432 ABCDGIKL IGBCADLK
433 ABCDGIJL CJBDAGLI
434 ABCDGIJK CJBDAGIK
435 ABCDGHKL HGBCADLK
436 ABCDGHJL HGBCADLJ
437 ABCDGHJK HGBCADJK
438 ABCDGHIL HGBCADLI
439 ABCDGHIK HGBCADIK
440 ABCDGHIJ HGBCADIJ
441 ABCDFJKL CJBDAFLK
442 ABCDFIKL CIBDAFLK
443 ABCDFIJL CJBDAFLI
444 ABCDFIJK CJBDAFIK
445 ABCDFHKL HFBCADLK
446 ABCDFHJL CJBDAFLH
447 ABCDFHJK HJBCAFDK
448 ABCDFHIL HFBCADLI
449 ABCDFHIK HFBCADIK
450 ABCDFHIJ HJBCAFDI
451 ABCDFGKL CGBDAFLK
452 ABCDFGJL CGBDAFLJ
453 ABCDFGJK CGBDAFJK
454 ABCDFGIL CGBDAFLI
455 ABCDFGIK CGBDAFIK
456 ABCDFGIJ CGBDAFIJ
457 ABCDFGHL CGBDAFLH
458 ABCDFGHK HGBCAFDK
459 ABCDFGHJ HGBCAFDJ
460 ABCDFGHI HGBCAFDI
461 ABCDEJKL EJBCADLK
462 ABCDEIKL EIBCADLK
463 ABCDEIJL EJBCADLI
464 ABCDEIJK EJBCADIK
465 ABCDEHKL HEBCADLK
466 ABCDEHJL HJBCADLE
467 ABCDEHJK HJBCADEK
468 ABCDEHIL HEBCADLI
469 ABCDEHIK HEBCADIK
470 ABCDEHIJ HJBCADEI
471 ABCDEGKL EGBCADLK
472 ABCDEGJL EGBCADLJ
473 ABCDEGJK EGBCADJK
474 ABCDEGIL EGBCADLI
475 ABCDEGIK EGBCADIK
476 ABCDEGIJ EGBCADIJ
477 ABCDEGHL HGBCADLE
478 ABCDEGHK HGBCADEK
479 ABCDEGHJ HGBCADEJ
480 ABCDEGHI HGBCADEI
481 ABCDEFKL CEBDAFLK
482 ABCDEFJL CJBDAFLE
483 ABCDEFJK CJBDAFEK
484 ABCDEFIL CEBDAFLI
485 ABCDEFIK CEBDAFIK
486 ABCDEFIJ CJBDAFEI
487 ABCDEFHL HFBCADLE
488 ABCDEFHK HEBCAFDK
489 ABCDEFHJ HJBCAFDE
490 ABCDEFHI HEBCAFDI
491 ABCDEFGL CGBDAFLE
492 ABCDEFGK CGBDAFEK
493 ABCDEFGJ CGBDAFEJ
494 ABCDEFGI CGBDAFEI
495 ABCDEFGH HGBCAFDE
`;

// ---- パース ----
const rows = RAW.trim().split('\n').map((line) => {
  const [num, groups, assign] = line.trim().split(/\s+/);
  return { num: Number(num), groups, assign };
});

// ---- 検証 ----
const errors = [];
const seenKeys = new Set();
const table = {}; // key(sorted groups) -> assignment(slot order)

for (const { num, groups, assign } of rows) {
  const groupArr = groups.split('');
  const assignArr = assign.split('');

  // 2) 通過グループが相異なる8個 (A-L)
  const gset = new Set(groupArr);
  if (groupArr.length !== 8 || gset.size !== 8 || groupArr.some((g) => !'ABCDEFGHIJKL'.includes(g))) {
    errors.push(`行${num}: 通過グループが不正 "${groups}"`);
    continue;
  }
  // 割り当ても8文字
  if (assignArr.length !== 8) {
    errors.push(`行${num}: 割り当てが8文字でない "${assign}"`);
    continue;
  }
  // 4) 割り当てが通過グループの順列か（過不足なし・重複なし）
  const sortedGroups = [...groupArr].sort().join('');
  const sortedAssign = [...assignArr].sort().join('');
  if (sortedGroups !== sortedAssign) {
    errors.push(`行${num} [${groups}]: 割り当て"${assign}"が通過グループの順列でない (ソート: ${sortedAssign} ≠ ${sortedGroups})`);
  }
  // 5) プール制約
  for (let i = 0; i < SLOTS.length; i++) {
    const slot = SLOTS[i];
    const g = assignArr[i];
    if (!POOLS[slot].includes(g)) {
      errors.push(`行${num} [${groups}]: スロット1${slot} に 3${g} は不可 (プール ${POOLS[slot].join('')})`);
    }
  }
  // 3) キー重複チェック
  if (seenKeys.has(sortedGroups)) {
    errors.push(`行${num}: 通過グループ集合の重複 "${sortedGroups}"`);
  }
  seenKeys.add(sortedGroups);
  table[sortedGroups] = assign;
}

// 1) 行数 & 全網羅チェック
if (rows.length !== 495) errors.push(`行数が495でない: ${rows.length}`);

// C(12,8) を生成して網羅を確認
function combos(arr, k, start = 0, cur = [], out = []) {
  if (cur.length === k) { out.push(cur.join('')); return out; }
  for (let i = start; i < arr.length; i++) { cur.push(arr[i]); combos(arr, k, i + 1, cur, out); cur.pop(); }
  return out;
}
const allCombos = combos('ABCDEFGHIJKL'.split(''), 8);
for (const c of allCombos) {
  if (!table[c]) errors.push(`未収録の組み合わせ: ${c}`);
}

// ---- 結果 ----
if (errors.length > 0) {
  console.error(`❌ 検証失敗 (${errors.length}件):`);
  for (const e of errors.slice(0, 50)) console.error('  - ' + e);
  if (errors.length > 50) console.error(`  ...他 ${errors.length - 50}件`);
  process.exit(1);
}

console.log(`✅ 検証OK: 495行すべてが プール制約・順列・全網羅 を満たしています。`);

// ---- 出力 ----
const outPath = resolve(__dirname, '../src/data/thirdPlaceAllocation.ts');
mkdirSync(dirname(outPath), { recursive: true });

const entries = Object.keys(table).sort().map((k) => `  '${k}': '${table[k]}',`).join('\n');

const ts = `// =============================================================================
// AUTO-GENERATED — 手動で編集しないこと。
// scripts/build-annexc.mjs により FIFA WC2026 公式 付属書C から生成。
// =============================================================================

// 3位チームと対戦する1位スロット（公式表の列順）
export const THIRD_PLACE_SLOTS = ['A', 'B', 'D', 'E', 'G', 'I', 'K', 'L'] as const;

// key: 通過した3位の所属グループ8つをアルファベット順に連結した文字列
// value: 各スロット(THIRD_PLACE_SLOTS の順)に入る3位の所属グループ
const ANNEX_C: Record<string, string> = {
${entries}
};

/**
 * 付属書Cに基づき、3位通過8グループを R32 の各1位スロットへ割り当てる。
 * @param qualifiedThirdGroups 3位通過した8グループ（順不同）
 * @returns 例 { A: 'C', B: 'J', D: 'I', E: 'F', G: 'H', I: 'G', K: 'L', L: 'K' }
 *          （1Aスロットには C組の3位、1Bスロットには J組の3位 …）
 *          8グループちょうどで無い／表に無い場合は null
 */
export function allocateThirdPlaceByAnnexC(
  qualifiedThirdGroups: string[]
): Record<string, string> | null {
  if (qualifiedThirdGroups.length !== 8) return null;
  const key = [...qualifiedThirdGroups].sort().join('');
  const assign = ANNEX_C[key];
  if (!assign) return null;
  const result: Record<string, string> = {};
  THIRD_PLACE_SLOTS.forEach((slot, i) => {
    result[slot] = assign[i];
  });
  return result;
}
`;

writeFileSync(outPath, ts, 'utf8');
console.log(`✅ 生成: ${outPath} (${Object.keys(table).length}件)`);
