import type { Match } from './types';

export const officialMatches: Match[] = [
  {
    id: 'A-MEX-RSA',
    group: 'A',
    homeTeam: 'MEX',
    awayTeam: 'RSA',
    homeScore: null,
    awayScore: null,
    date: '2026-06-12',
    time: '04:00',
    matchDay: 1,
  },
  {
    id: 'A-KOR-CZE',
    group: 'A',
    homeTeam: 'KOR',
    awayTeam: 'CZE',
    homeScore: null,
    awayScore: null,
    date: '2026-06-12',
    time: '11:00',
    matchDay: 1,
  },
  {
    id: 'A-CZE-RSA',
    group: 'A',
    homeTeam: 'CZE',
    awayTeam: 'RSA',
    homeScore: null,
    awayScore: null,
    date: '2026-06-19',
    time: '01:00',
    matchDay: 2,
  },
  {
    id: 'A-MEX-KOR',
    group: 'A',
    homeTeam: 'MEX',
    awayTeam: 'KOR',
    homeScore: null,
    awayScore: null,
    date: '2026-06-19',
    time: '10:00',
    matchDay: 2,
  },
  {
    id: 'A-CZE-MEX',
    group: 'A',
    homeTeam: 'CZE',
    awayTeam: 'MEX',
    homeScore: null,
    awayScore: null,
    date: '2026-06-25',
    time: '10:00',
    matchDay: 3,
  },
  {
    id: 'A-RSA-KOR',
    group: 'A',
    homeTeam: 'RSA',
    awayTeam: 'KOR',
    homeScore: null,
    awayScore: null,
    date: '2026-06-25',
    time: '10:00',
    matchDay: 3,
  },
  {
    id: 'B-CAN-BIH',
    group: 'B',
    homeTeam: 'CAN',
    awayTeam: 'BIH',
    homeScore: null,
    awayScore: null,
    date: '2026-06-13',
    time: '04:00',
    matchDay: 1,
  },
  {
    id: 'B-QAT-SUI',
    group: 'B',
    homeTeam: 'QAT',
    awayTeam: 'SUI',
    homeScore: null,
    awayScore: null,
    date: '2026-06-14',
    time: '04:00',
    matchDay: 1,
  },
  {
    id: 'B-SUI-BIH',
    group: 'B',
    homeTeam: 'SUI',
    awayTeam: 'BIH',
    homeScore: null,
    awayScore: null,
    date: '2026-06-19',
    time: '04:00',
    matchDay: 2,
  },
  {
    id: 'B-CAN-QAT',
    group: 'B',
    homeTeam: 'CAN',
    awayTeam: 'QAT',
    homeScore: null,
    awayScore: null,
    date: '2026-06-19',
    time: '07:00',
    matchDay: 2,
  },
  {
    id: 'B-SUI-CAN',
    group: 'B',
    homeTeam: 'SUI',
    awayTeam: 'CAN',
    homeScore: null,
    awayScore: null,
    date: '2026-06-25',
    time: '04:00',
    matchDay: 3,
  },
  {
    id: 'B-BIH-QAT',
    group: 'B',
    homeTeam: 'BIH',
    awayTeam: 'QAT',
    homeScore: null,
    awayScore: null,
    date: '2026-06-25',
    time: '04:00',
    matchDay: 3,
  },
  {
    id: 'C-BRA-MAR',
    group: 'C',
    homeTeam: 'BRA',
    awayTeam: 'MAR',
    homeScore: null,
    awayScore: null,
    date: '2026-06-14',
    time: '07:00',
    matchDay: 1,
  },
  {
    id: 'C-HAI-SCO',
    group: 'C',
    homeTeam: 'HAI',
    awayTeam: 'SCO',
    homeScore: null,
    awayScore: null,
    date: '2026-06-14',
    time: '10:00',
    matchDay: 1,
  },
  {
    id: 'C-SCO-MAR',
    group: 'C',
    homeTeam: 'SCO',
    awayTeam: 'MAR',
    homeScore: null,
    awayScore: null,
    date: '2026-06-20',
    time: '07:00',
    matchDay: 2,
  },
  {
    id: 'C-BRA-HAI',
    group: 'C',
    homeTeam: 'BRA',
    awayTeam: 'HAI',
    homeScore: null,
    awayScore: null,
    date: '2026-06-20',
    time: '10:00',
    matchDay: 2,
  },
  {
    id: 'C-SCO-BRA',
    group: 'C',
    homeTeam: 'SCO',
    awayTeam: 'BRA',
    homeScore: null,
    awayScore: null,
    date: '2026-06-25',
    time: '07:00',
    matchDay: 3,
  },
  {
    id: 'C-MAR-HAI',
    group: 'C',
    homeTeam: 'MAR',
    awayTeam: 'HAI',
    homeScore: null,
    awayScore: null,
    date: '2026-06-25',
    time: '07:00',
    matchDay: 3,
  },
  {
    id: 'D-USA-PAR',
    group: 'D',
    homeTeam: 'USA',
    awayTeam: 'PAR',
    homeScore: null,
    awayScore: null,
    date: '2026-06-13',
    time: '10:00',
    matchDay: 1,
  },
  {
    id: 'D-AUS-TUR',
    group: 'D',
    homeTeam: 'AUS',
    awayTeam: 'TUR',
    homeScore: null,
    awayScore: null,
    date: '2026-06-14',
    time: '13:00',
    matchDay: 1,
  },
  {
    id: 'D-USA-AUS',
    group: 'D',
    homeTeam: 'USA',
    awayTeam: 'AUS',
    homeScore: null,
    awayScore: null,
    date: '2026-06-20',
    time: '04:00',
    matchDay: 2,
  },
  {
    id: 'D-TUR-PAR',
    group: 'D',
    homeTeam: 'TUR',
    awayTeam: 'PAR',
    homeScore: null,
    awayScore: null,
    date: '2026-06-20',
    time: '13:00',
    matchDay: 2,
  },
  {
    id: 'D-TUR-USA',
    group: 'D',
    homeTeam: 'TUR',
    awayTeam: 'USA',
    homeScore: null,
    awayScore: null,
    date: '2026-06-26',
    time: '11:00',
    matchDay: 3,
  },
  {
    id: 'D-PAR-AUS',
    group: 'D',
    homeTeam: 'PAR',
    awayTeam: 'AUS',
    homeScore: null,
    awayScore: null,
    date: '2026-06-26',
    time: '11:00',
    matchDay: 3,
  },
  {
    id: 'E-GER-CUW',
    group: 'E',
    homeTeam: 'GER',
    awayTeam: 'CUW',
    homeScore: null,
    awayScore: null,
    date: '2026-06-15',
    time: '02:00',
    matchDay: 1,
  },
  {
    id: 'E-CIV-ECU',
    group: 'E',
    homeTeam: 'CIV',
    awayTeam: 'ECU',
    homeScore: null,
    awayScore: null,
    date: '2026-06-15',
    time: '08:00',
    matchDay: 1,
  },
  {
    id: 'E-GER-CIV',
    group: 'E',
    homeTeam: 'GER',
    awayTeam: 'CIV',
    homeScore: null,
    awayScore: null,
    date: '2026-06-21',
    time: '05:00',
    matchDay: 2,
  },
  {
    id: 'E-ECU-CUW',
    group: 'E',
    homeTeam: 'ECU',
    awayTeam: 'CUW',
    homeScore: null,
    awayScore: null,
    date: '2026-06-21',
    time: '09:00',
    matchDay: 2,
  },
  {
    id: 'E-CUW-CIV',
    group: 'E',
    homeTeam: 'CUW',
    awayTeam: 'CIV',
    homeScore: null,
    awayScore: null,
    date: '2026-06-26',
    time: '05:00',
    matchDay: 3,
  },
  {
    id: 'E-ECU-GER',
    group: 'E',
    homeTeam: 'ECU',
    awayTeam: 'GER',
    homeScore: null,
    awayScore: null,
    date: '2026-06-26',
    time: '05:00',
    matchDay: 3,
  },
  {
    id: 'F-NED-JPN',
    group: 'F',
    homeTeam: 'NED',
    awayTeam: 'JPN',
    homeScore: null,
    awayScore: null,
    date: '2026-06-15',
    time: '05:00',
    matchDay: 1,
  },
  {
    id: 'F-SWE-TUN',
    group: 'F',
    homeTeam: 'SWE',
    awayTeam: 'TUN',
    homeScore: null,
    awayScore: null,
    date: '2026-06-15',
    time: '11:00',
    matchDay: 1,
  },
  {
    id: 'F-NED-SWE',
    group: 'F',
    homeTeam: 'NED',
    awayTeam: 'SWE',
    homeScore: null,
    awayScore: null,
    date: '2026-06-21',
    time: '02:00',
    matchDay: 2,
  },
  {
    id: 'F-TUN-JPN',
    group: 'F',
    homeTeam: 'TUN',
    awayTeam: 'JPN',
    homeScore: null,
    awayScore: null,
    date: '2026-06-21',
    time: '13:00',
    matchDay: 2,
  },
  {
    id: 'F-JPN-SWE',
    group: 'F',
    homeTeam: 'JPN',
    awayTeam: 'SWE',
    homeScore: null,
    awayScore: null,
    date: '2026-06-26',
    time: '08:00',
    matchDay: 3,
  },
  {
    id: 'F-TUN-NED',
    group: 'F',
    homeTeam: 'TUN',
    awayTeam: 'NED',
    homeScore: null,
    awayScore: null,
    date: '2026-06-26',
    time: '08:00',
    matchDay: 3,
  },
  {
    id: 'G-BEL-EGY',
    group: 'G',
    homeTeam: 'BEL',
    awayTeam: 'EGY',
    homeScore: null,
    awayScore: null,
    date: '2026-06-16',
    time: '04:00',
    matchDay: 1,
  },
  {
    id: 'G-IRN-NZL',
    group: 'G',
    homeTeam: 'IRN',
    awayTeam: 'NZL',
    homeScore: null,
    awayScore: null,
    date: '2026-06-16',
    time: '10:00',
    matchDay: 1,
  },
  {
    id: 'G-BEL-IRN',
    group: 'G',
    homeTeam: 'BEL',
    awayTeam: 'IRN',
    homeScore: null,
    awayScore: null,
    date: '2026-06-22',
    time: '04:00',
    matchDay: 2,
  },
  {
    id: 'G-NZL-EGY',
    group: 'G',
    homeTeam: 'NZL',
    awayTeam: 'EGY',
    homeScore: null,
    awayScore: null,
    date: '2026-06-22',
    time: '10:00',
    matchDay: 2,
  },
  {
    id: 'G-EGY-IRN',
    group: 'G',
    homeTeam: 'EGY',
    awayTeam: 'IRN',
    homeScore: null,
    awayScore: null,
    date: '2026-06-27',
    time: '12:00',
    matchDay: 3,
  },
  {
    id: 'G-NZL-BEL',
    group: 'G',
    homeTeam: 'NZL',
    awayTeam: 'BEL',
    homeScore: null,
    awayScore: null,
    date: '2026-06-27',
    time: '12:00',
    matchDay: 3,
  },
  {
    id: 'H-ESP-CPV',
    group: 'H',
    homeTeam: 'ESP',
    awayTeam: 'CPV',
    homeScore: null,
    awayScore: null,
    date: '2026-06-16',
    time: '01:00',
    matchDay: 1,
  },
  {
    id: 'H-KSA-URU',
    group: 'H',
    homeTeam: 'KSA',
    awayTeam: 'URU',
    homeScore: null,
    awayScore: null,
    date: '2026-06-16',
    time: '07:00',
    matchDay: 1,
  },
  {
    id: 'H-ESP-KSA',
    group: 'H',
    homeTeam: 'ESP',
    awayTeam: 'KSA',
    homeScore: null,
    awayScore: null,
    date: '2026-06-22',
    time: '01:00',
    matchDay: 2,
  },
  {
    id: 'H-URU-CPV',
    group: 'H',
    homeTeam: 'URU',
    awayTeam: 'CPV',
    homeScore: null,
    awayScore: null,
    date: '2026-06-22',
    time: '07:00',
    matchDay: 2,
  },
  {
    id: 'H-CPV-KSA',
    group: 'H',
    homeTeam: 'CPV',
    awayTeam: 'KSA',
    homeScore: null,
    awayScore: null,
    date: '2026-06-27',
    time: '09:00',
    matchDay: 3,
  },
  {
    id: 'H-URU-ESP',
    group: 'H',
    homeTeam: 'URU',
    awayTeam: 'ESP',
    homeScore: null,
    awayScore: null,
    date: '2026-06-27',
    time: '09:00',
    matchDay: 3,
  },
  {
    id: 'I-FRA-SEN',
    group: 'I',
    homeTeam: 'FRA',
    awayTeam: 'SEN',
    homeScore: null,
    awayScore: null,
    date: '2026-06-17',
    time: '04:00',
    matchDay: 1,
  },
  {
    id: 'I-IRQ-NOR',
    group: 'I',
    homeTeam: 'IRQ',
    awayTeam: 'NOR',
    homeScore: null,
    awayScore: null,
    date: '2026-06-17',
    time: '07:00',
    matchDay: 1,
  },
  {
    id: 'I-FRA-IRQ',
    group: 'I',
    homeTeam: 'FRA',
    awayTeam: 'IRQ',
    homeScore: null,
    awayScore: null,
    date: '2026-06-23',
    time: '06:00',
    matchDay: 2,
  },
  {
    id: 'I-NOR-SEN',
    group: 'I',
    homeTeam: 'NOR',
    awayTeam: 'SEN',
    homeScore: null,
    awayScore: null,
    date: '2026-06-23',
    time: '09:00',
    matchDay: 2,
  },
  {
    id: 'I-NOR-FRA',
    group: 'I',
    homeTeam: 'NOR',
    awayTeam: 'FRA',
    homeScore: null,
    awayScore: null,
    date: '2026-06-27',
    time: '04:00',
    matchDay: 3,
  },
  {
    id: 'I-SEN-IRQ',
    group: 'I',
    homeTeam: 'SEN',
    awayTeam: 'IRQ',
    homeScore: null,
    awayScore: null,
    date: '2026-06-27',
    time: '04:00',
    matchDay: 3,
  },
  {
    id: 'J-ARG-ALG',
    group: 'J',
    homeTeam: 'ARG',
    awayTeam: 'ALG',
    homeScore: null,
    awayScore: null,
    date: '2026-06-17',
    time: '10:00',
    matchDay: 1,
  },
  {
    id: 'J-AUT-JOR',
    group: 'J',
    homeTeam: 'AUT',
    awayTeam: 'JOR',
    homeScore: null,
    awayScore: null,
    date: '2026-06-17',
    time: '13:00',
    matchDay: 1,
  },
  {
    id: 'J-ARG-AUT',
    group: 'J',
    homeTeam: 'ARG',
    awayTeam: 'AUT',
    homeScore: null,
    awayScore: null,
    date: '2026-06-23',
    time: '02:00',
    matchDay: 2,
  },
  {
    id: 'J-JOR-ALG',
    group: 'J',
    homeTeam: 'JOR',
    awayTeam: 'ALG',
    homeScore: null,
    awayScore: null,
    date: '2026-06-23',
    time: '12:00',
    matchDay: 2,
  },
  {
    id: 'J-ALG-AUT',
    group: 'J',
    homeTeam: 'ALG',
    awayTeam: 'AUT',
    homeScore: null,
    awayScore: null,
    date: '2026-06-28',
    time: '11:00',
    matchDay: 3,
  },
  {
    id: 'J-JOR-ARG',
    group: 'J',
    homeTeam: 'JOR',
    awayTeam: 'ARG',
    homeScore: null,
    awayScore: null,
    date: '2026-06-28',
    time: '11:00',
    matchDay: 3,
  },
  {
    id: 'K-POR-COD',
    group: 'K',
    homeTeam: 'POR',
    awayTeam: 'COD',
    homeScore: null,
    awayScore: null,
    date: '2026-06-18',
    time: '02:00',
    matchDay: 1,
  },
  {
    id: 'K-UZB-COL',
    group: 'K',
    homeTeam: 'UZB',
    awayTeam: 'COL',
    homeScore: null,
    awayScore: null,
    date: '2026-06-18',
    time: '11:00',
    matchDay: 1,
  },
  {
    id: 'K-POR-UZB',
    group: 'K',
    homeTeam: 'POR',
    awayTeam: 'UZB',
    homeScore: null,
    awayScore: null,
    date: '2026-06-24',
    time: '02:00',
    matchDay: 2,
  },
  {
    id: 'K-COL-COD',
    group: 'K',
    homeTeam: 'COL',
    awayTeam: 'COD',
    homeScore: null,
    awayScore: null,
    date: '2026-06-24',
    time: '11:00',
    matchDay: 2,
  },
  {
    id: 'K-COL-POR',
    group: 'K',
    homeTeam: 'COL',
    awayTeam: 'POR',
    homeScore: null,
    awayScore: null,
    date: '2026-06-28',
    time: '08:30',
    matchDay: 3,
  },
  {
    id: 'K-COD-UZB',
    group: 'K',
    homeTeam: 'COD',
    awayTeam: 'UZB',
    homeScore: null,
    awayScore: null,
    date: '2026-06-28',
    time: '08:30',
    matchDay: 3,
  },
  {
    id: 'L-ENG-CRO',
    group: 'L',
    homeTeam: 'ENG',
    awayTeam: 'CRO',
    homeScore: null,
    awayScore: null,
    date: '2026-06-18',
    time: '05:00',
    matchDay: 1,
  },
  {
    id: 'L-GHA-PAN',
    group: 'L',
    homeTeam: 'GHA',
    awayTeam: 'PAN',
    homeScore: null,
    awayScore: null,
    date: '2026-06-18',
    time: '08:00',
    matchDay: 1,
  },
  {
    id: 'L-ENG-GHA',
    group: 'L',
    homeTeam: 'ENG',
    awayTeam: 'GHA',
    homeScore: null,
    awayScore: null,
    date: '2026-06-24',
    time: '05:00',
    matchDay: 2,
  },
  {
    id: 'L-PAN-CRO',
    group: 'L',
    homeTeam: 'PAN',
    awayTeam: 'CRO',
    homeScore: null,
    awayScore: null,
    date: '2026-06-24',
    time: '08:00',
    matchDay: 2,
  },
  {
    id: 'L-PAN-ENG',
    group: 'L',
    homeTeam: 'PAN',
    awayTeam: 'ENG',
    homeScore: null,
    awayScore: null,
    date: '2026-06-28',
    time: '06:00',
    matchDay: 3,
  },
  {
    id: 'L-CRO-GHA',
    group: 'L',
    homeTeam: 'CRO',
    awayTeam: 'GHA',
    homeScore: null,
    awayScore: null,
    date: '2026-06-28',
    time: '06:00',
    matchDay: 3,
  },
];
